//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fleamarket_reviews
    {
        public int users_id { get; set; }
        public int fleamarkets_id { get; set; }
        public string text { get; set; }
        public int stars { get; set; }
    
        public virtual fleamarkets fleamarkets { get; set; }
        public virtual users users { get; set; }
    }
}
