//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fleamarket_openings
    {
        public int id { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
        public int fleamarkets_id { get; set; }
        public string description { get; set; }
    
        public virtual fleamarkets fleamarkets { get; set; }
    }
}
