//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.fleamarket_reviews = new HashSet<fleamarket_reviews>();
            this.fleamarkets = new HashSet<fleamarkets>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string password_hash { get; set; }
        public string salt { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime modified_on { get; set; }
    
        public virtual ICollection<fleamarket_reviews> fleamarket_reviews { get; set; }
        public virtual ICollection<fleamarkets> fleamarkets { get; set; }
    }
}
